[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "php82Extensions.zip", "nodejs"]

[phases.install]
cmds = ["composer install --optimize-autoloader --no-interaction --no-scripts"]

[phases.build]
cmds = ["php artisan config:cache", "npm install && npm run build"]