[variables]
    PHP_VERSION = '8.4'

[phases.setup]
    nixPkgs = ['...', 'php84', 'php84Packages.composer', 'nodejs_20']

[phases.install]
cmds = ["composer install --optimize-autoloader --no-interaction --no-scripts"]

[phases.build]
cmds = ["php artisan config:cache", "npm install && npm run build"]