[variables]
    NIXPACKS_NODE_VERSION = "22"
    NIXPACKS_PHP_VERSION = "8.4" 

[phases.setup]
    nixPkgs = ["php", "nginx", "nodejs_22", "phpPackages.composer"]

[phases.install]
cmds = ["composer install --optimize-autoloader --no-interaction --no-scripts"]

[phases.build]
cmds = ["php artisan config:cache", "npm install && npm run build"]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"